Clean up output

diff --git a/test/run-shared-integration-tests b/test/run-shared-integration-tests
--- a/test/run-shared-integration-tests
+++ b/test/run-shared-integration-tests
@@ -45,18 +45,18 @@ prefix() {
 # Prune installed dependencies
 #
 prune-dependencies() {
-    run npm prune --production | prefix "npm prune"
+    run npm prune --production 2>&1 | prefix "npm prune"
 
 	# install commander and tchannel because those are required by main.js
     # this is a temporary workaround until main.js is moved to it's own (sub-)module.
-	install-white-listed-dev-dependencies | prefix 'white-listed dev'
+	install-white-listed-dev-dependencies 2>&1 | prefix 'white-listed dev'
 }
 
 install-white-listed-dev-dependencies() {
 	for package in $white_listed_dev_dependencies; do
     	version=($(jq -r ".devDependencies.$package" package.json))
     	echo "Installing: ${package}@$version"
-    	output=$(npm install ${package}@$version 2>&1) || echo "failed to install ${package}: $output"
+    	output=$(run npm install ${package}@$version 2>&1) || (echo "failed to install ${package}:"; echo "$output")
 	done
 }
 
@@ -135,7 +135,7 @@ run-tests() {
 }
 
 # Prune installed dev dependencies
-prune-dependencies 2>&1
+prune-dependencies
 
 # Fetch and build in parallel
 fetch-ringpop-common 2>&1|prefix "fetch ringpop-common"
